export default {
  results: [{
    unit: 84,
    show_id: 60032563,
    title: 'Kill Bill: Vol. 2',
    releaseYear: '2004',
    rating: '3.8',
    category: 'Action & Adventure',
    showCast: 'Uma Thurman, David Carradine, Michael Madsen, Daryl Hannah, Gordon Liu, Michael Parks, Perla Haney-Jardine, Helen Kim, Claire Smithies, Clark Middleton',
    director: 'Quentin Tarantino',
    summary: 'The Bride has three left on her rampage list: Budd, Elle Driver and Bill himself. But when she arrives at Bill\'s house, she\'s in for a surprise.',
    poster: 'http://netflixroulette.net/api/posters/60032563.jpg',
    mediatype: 0,
    runtime: '137 min',
  }, {
    unit: 87,
    show_id: 60031236,
    title: 'Kill Bill: Vol. 1',
    releaseYear: '2003',
    rating: '3.8',
    category: 'Action & Adventure',
    showCast: 'Uma Thurman, Lucy Liu, Vivica A. Fox, Daryl Hannah, David Carradine, Michael Madsen, Julie Dreyfus, Chiaki Kuriyama, Sonny Chiba, Gordon Liu',
    director: 'Quentin Tarantino',
    summary: 'An assassin is shot by her ruthless employer, Bill, and other members of their assassination circle. But she lives -- and plots her vengeance.',
    poster: 'http://netflixroulette.net/api/posters/60031236.jpg',
    mediatype: 0,
    runtime: '111 min',
  }],
  film: {
    unit: 84,
    show_id: 60032563,
    title: 'Kill Bill: Vol. 2',
    releaseYear: '2004',
    rating: '3.8',
    category: 'Action & Adventure',
    showCast: 'Uma Thurman, David Carradine, Michael Madsen, Daryl Hannah, Gordon Liu, Michael Parks, Perla Haney-Jardine, Helen Kim, Claire Smithies, Clark Middleton',
    director: 'Quentin Tarantino',
    summary: 'The Bride has three left on her rampage list: Budd, Elle Driver and Bill himself. But when she arrives at Bill\'s house, she\'s in for a surprise.',
    poster: 'http://netflixroulette.net/api/posters/60032563.jpg',
    mediatype: 0,
    runtime: '137 min',
  },
};
